name: WolfColors
version: 1.0.1
description: Change your wolf's collar color!
author: cnaude
main: me.cnaude.plugin.WolfColors.WCMain
permissions:
  wolfcolors.wolfcolors:
    description: Allow a player to dye a wolf's collar.
    default: false